from typing import Any

class _HttpClient: 
    async def __aenter__(self) -> "_HttpClient": ...
    async def __aexit__(self, exc_type, exc, tb) -> None: ...
    async def get(self, url: str, params: dict[str, Any] | None = None) -> Any: ...


def get_http_client() -> _HttpClient: ...
def with_retry(*args: Any, **kwargs: Any) -> Any: ...
