def spearman_block_ci(
    pairs: list, *, block_length: int = ..., n_boot: int = ...,
    confidence: float = ..., seed: int = ...,
) -> tuple[float | None, float | None, float | None]: ...
def spearman(x: list[float], y: list[float]) -> float | None: ...
def max_drawdown(equity: list[float]) -> float: ...
def probabilistic_sharpe_ratio(returns: list, benchmark_sharpe: float = ...) -> float: ...
