def spearman_block_ci(*args: object, **kwargs: object) -> tuple[object, object, object]: ...
def spearman(x: list[float], y: list[float]) -> float | None: ...
def max_drawdown(equity: list[float]) -> float: ...
def probabilistic_sharpe_ratio(returns: list, benchmark_sharpe: float = ...) -> float: ...
