import pathlib,json,datetime,hashlib,gzip
r=pathlib.Path(__file__).resolve().parents[1];old=json.loads((r/'RESULTS.json').read_bytes())['results']['F03']
samples=[]
for s in old['samples']:
 if s['status']=='ABSENT':samples.append({'symbol':s['symbol'],'status':'ABSENT_IN_THIS_PANEL'});continue
 first=datetime.datetime.fromtimestamp(s['first_open_ms']/1000,datetime.UTC).isoformat();last=datetime.datetime.fromtimestamp(s['last_open_ms']/1000,datetime.UTC).isoformat()
 samples.append({'symbol':s['symbol'],'event_at':'REPRESENTABLE: open_ms; daily closure uses close_ms','instrument_id':'PARTIAL: symbol + source; canonical asset history/quote/contract identity not fully typed','received_at':'ACQUISITION_METADATA: finalized_at_utc; can enforce no use before this acquisition, not prove older first receipt','historical_published_at':'UNKNOWN: close_ms is market period closure, not observed publication','eligibility_history':'NOT_ESTABLISHED for full universe at every decision; posthoc identity_events explicitly limited to13 censored observations','source_receipt_hash':'PARTIAL: normalized checksum/acquisition provenance exist; no row-level first-publication evidence established by this review','historical_event_range':[first,last],'acquisition_at':s['collected_at'],'missing_internal_days':s['missing_internal_days'],'state':'BLOCKED_FOR_NEW_PIT_ECONOMIC_TEST'})
out={'observed_at':datetime.datetime.now(datetime.UTC).isoformat(),'reason':'Semantic correction to initial raw field-name diagnostic, preregistered in ADVERSARIAL_PROTOCOL.json. Missing exact names alone do not mean missing information.','samples':samples,'synthetic_control_result':old['membership_controls'],'access_scope':'Only previously examined retrospective panel, not forward/holdout files. No prices or returns evaluated.','gate_decision':'BLOCKED_DATA; not rejection of residual ranking. Full row-level publication/eligibility proof and unused evaluation period absent.','rows_admissible_percentage':'UNKNOWN; do not report 0% from missing schema names','known_metadata':{'declared_rows':old['panel_declared_rows'],'pairs':old['pair_count'],'missing_days':old['missing_days_metadata_sum'],'identity_events':old['identity_events']},'input_hashes':old['input_hashes'],'new_implementations_integrated':False}
with (r/'F03_SEMANTIC_GATE.json').open('x',encoding='utf-8') as f:json.dump(out,f,ensure_ascii=False,indent=2)
print(json.dumps({'decision':out['gate_decision'],'samples':len(samples)},ensure_ascii=False))
