import pathlib,json,datetime
R=pathlib.Path(__file__).resolve().parents[1]
def read(n):return json.loads((R/n).read_bytes())
def write(n,x):(R/n).write_text(json.dumps(x,indent=2,ensure_ascii=False),encoding='utf-8')
hypotheses=[
 {'id':'H_CLOCK_1','hypothesis':'Offset between local and remote clocks','for':['T minus local receipt positive in 12/12, range 408.6478 to 446.958 ms','Both local and source series monotonic in observed sample'],'against':['No synchronization log or independent simultaneous time reference','Stable-looking difference also compatible with timestamp generation semantics'],'possible_test':'Contemporaneous calibrated clock/NTP/PTP evidence and documented source timestamp meaning; current clock measurement cannot back-prove offset','conclusion':'COMPATIBLE_NOT_IDENTIFIED'},
 {'id':'H_CLOCK_2','hypothesis':'Local wall-clock adjustment or timestamp instrumentation error','for':['time.time_ns is wall clock; no monotonic clock recorded','No record of clock corrections or timing accuracy'],'against':['No backward step in the 12 observed request/receipt sequences; all receipts after requests','Stable offset across samples disfavors one isolated transient, without ruling out a persistent local bias'],'possible_test':'Saved system clock-adjustment logs and paired monotonic/wall timestamps at collection; none in this capture','conclusion':'NOT_IDENTIFIED; observed reversal absent, accuracy unknown'},
 {'id':'H_CLOCK_3','hypothesis':'Wrong unit conversion or arithmetic','for':['Archived depth schema documenting T/E units is absent from bounded bundle'],'against':['Integer calculation independently exact: T*10^6 - received_ns = 410300800 ns','Milliseconds align source T with the collection epoch; seconds/microseconds do not','Frozen local source proves request/receipt nanoseconds'],'possible_test':'Historical depth API schema for exact endpoint/version; separate raw-unit validation','conclusion':'ARITHMETIC_ERROR_REJECTED; primary source unit/semantic proof still incomplete'},
 {'id':'H_CLOCK_4','hypothesis':'T/E describe a different instant from the event/publication assumed','for':['Only literal T/E keys preserved; exact economic semantics absent','E greater than T by 2 to 5 raw ticks in saved books'],'against':['Ordering and monotonicity are consistent with ordinary event/response labeling, but do not identify it'],'possible_test':'Archived source specification and corresponding release/version; no automatic interpretation from current docs','conclusion':'COMPATIBLE_NOT_IDENTIFIED'},
 {'id':'H_CLOCK_5','hypothesis':'Wrong body/receipt association or simple cache explanation','for':['Two exchangeInfo acquisitions have identical body and older body serverTime; freshness cannot follow body timestamp alone'],'against':['All diagnostic bodies match per-name SHA-256; frozen collector records response metadata around same send','Old cached data alone would not explain future timestamps if clocks were synchronized and timestamp meant an occurred event'],'possible_test':'Verify preserved name/hash associations (executed); inspect HTTP Age/Date/cache headers and trace IDs (not retained)','conclusion':'HASH_MISASSOCIATION_NOT_OBSERVED; cache mechanism not proven and insufficient alone'},
 {'id':'H_CLOCK_6','hypothesis':'Remote timestamp-generation error','for':['Remote timestamps exceed local receipt under ms interpretation'],'against':['No independent accurate reference; the same observation is explained by local offset or semantic difference'],'possible_test':'Independent contemporary remote/local reference or provider incident evidence specific to capture interval','conclusion':'NOT_IDENTIFIED; no attribution of fault to exchange'}]
write('CLOCK_HYPOTHESES.json',{'overall':'CAUSE_UNKNOWN','hypotheses':hypotheses})
requirements=[]
def row(field,why,need,local,recover,gate,action):requirements.append({'missing_field':field,'why_it_matters':why,'necessary_evidence':need,'exists_locally_in_bounded_scope':local,'legitimate_recovery':recover,'blocks':gate,'next_action':action})
row('quantity_unit','Defines exposure; contracts and base units differ','Dated exact spot/depth and USD-M contract specifications defining order/book quantity and lot unit','PARTIAL: quantity/volume labels and LOT_SIZE values; no complete unit contract','Historical source could prove it; receipt fields alone cannot','F04','Future targeted historical specification search; no convention default')
row('price_unit','Distinguishes USDT/BTC from USD/BTC or inverse quotation','Dated quote/price definition tied to instrument and metric','PARTIAL: base/quote fields and named prices; explicit full unit linkage absent','Potentially recoverable from archived contract/API specification, not ticker','F04','Keep NOT_PROVEN until exact dated specification')
row('settlement_asset','Defines actual payout currency','Historical contract settlement rule for BTCUSDT and BTCUSDT_261225, and spot settlement terms','NOT_FOUND; marginAsset=USDT is preserved but not settlement','Not derivable from marginAsset; requires separate dated terms','F04','Seek specific archived contract settlement specification in a later authorized phase')
row('multiplier','Converts contractual quantity to exposure','Instrument-specific contract size/multiplier, or explicit one-unit relationship, versioned','NOT_FOUND; no contractSize in sampled rows; LOT_SIZE step is not multiplier','Not derivable from precision/lot filters; external historical terms may recover','F04','Keep UNKNOWN; do not default to 1')
row('linear_inverse / payoff','Determines PnL equation and currency','Dated payoff equation, price basis and payout currency for exact instrument','NOT_FOUND; U_MARGINED/PERPETUAL labels alone insufficient','Not uniquely identifiable from sample prices or code assumptions','F04','No generic perpetual equation; archive specification needed')
row('margin/collateral semantics','Defines capital constraints and treatment of collateral','Dated margin mode, collateral rules, haircuts, valuation, tiers and relevant account configuration','PARTIAL: marginAsset and percent fields; no complete rule/account context','Public historical rules may be recoverable; absent historical account state cannot be synthesized','F04','Separate public contract gate from future scoped account/capital assumptions')
row('expiry semantics','Defines maturity; not source availability','Contract deliveryDate with exact unit/event definition and dated specification','PARTIAL: BTCUSDT_261225 raw deliveryDate present; decoded 2026-12-25 08:00 UTC','Raw declared date recovered; old-calendar extrapolation and perpetual sentinel not proven','F04 dated','Use literal field only at collection; do not infer from ticker')
row('price_type / executable status','Mark/trade/book have different uses','Endpoint/field mapping and, for actual execution, explicit fill evidence','PARTIAL: trade/mark endpoint distinction and displayed ask preserved; fill absent','Metric distinction recoverable now; realized fills unrecorded cannot be fabricated','F04','Allow semantic checks; refuse mark-as-fill and trade-as-mark')
row('funding position basis / direction / currency','A rate is insufficient to calculate cash','Versioned funding event formula, eligible position, payer/payee direction, currency and schedule','NOT_FOUND; 33 rate observations with fundingTime and markPrice preserved','Requires historical rules; actual account settlements require account ledger that was not captured','F04 funding','FUNDING_REPLAY_NOT_PROVEN')
row('funding interval / eligibility','Determines which event applies to a position','Historical rule for interval/event boundary and eligibility','PARTIAL: observed deltas 28799974–28800013 candidate ms; not proof of fixed 8h schedule','Specific historical schedule may recover; actual eligibility not in rates alone','F04 funding','Keep rule unknown; no cash conversion')
row('contract_version / valid_from / valid_until','Prevents applying later terms to old observations','Effective-dated terms, immutable source version and change history','NOT_FOUND; content hashes and collection times only','Potentially from historical archived specifications; hashes alone cannot recover absent revisions','F03,F04','CURRENT_ONLY; earlier use is RETROACTIVE_ASSUMPTION')
row('source publication time','Needed for historical information availability','Original publication/distribution timestamp or contemporaneous receipt before cutoff','NOT_FOUND; later ingestion, candle open/close and HTTP Date are not original publication','Not reconstructible from captured fields; an independent contemporary archive could help','F03','Block earlier cutoff; do not use date labels as availability')
row('listing/delisting/eligibility history','Avoids survivorship and universe backfill','Complete effective-dated membership events with information availability','NOT_FOUND; current status/onboardDate and BTC-only bundle do not cover universe','Structurally absent from this BTC bundle; separate historical universe evidence required','F03','No broad collection now; maintain BLOCKED_CURRENT_EVIDENCE')
row('revision control','Prevents selecting future-corrected values','All necessary as-of versions and when each became available','PARTIAL: exact observed hashes; official saved README says archives can be updated','Unrecorded versions cannot be regenerated from final body or checksum; external dated copies may exist','F03,F04','Preserve observed versions; refuse historical first-vintage claim')
row('T/E unit and meaning','Prevents assigning remote time to wrong event','Archived depth endpoint schema with release mapping','NOT_FOUND in scope; candidate ms interpretation only','Specific historical API reference may recover meaning, not clock calibration','F04 temporal','Keep literal raw fields and conditional arithmetic')
row('remote/local offset and uncertainty','Allows valid cross-clock cutoff comparison','Contemporaneous clock calibration and uncertainty bounds, or independently timestamped synchronized trace','NOT_FOUND; no NTP/PTP, monotonic pairs, trusted response timing','Not identifiable from these recorded clocks alone; current calibration cannot recover past offset','F04 temporal','CAUSE_UNKNOWN; OBSERVED only, no economic eligibility by max')
row('source response time','Distinguishes event from response production','Documented response-time clock or trustworthy server timing headers with calibration','NOT_FOUND for diagnostic; body serverTime repeated across acquisitions','Absent header/trace cannot be recovered from body alone','F04 temporal','Do not label E or serverTime as response time')
row('ingestion/normalization time','Separates receive from persist/transform','Contemporaneous write/normalization event log','NOT_FOUND in original collector; only time around send retained','STRUCTURALLY_UNRECOVERABLE_FROM_CAPTURED_FIELDS unless an independent original log is later found','Temporal provenance','Use UNKNOWN; current file mtime/normalization execution is not historical evidence')
write('EVIDENCE_REQUIREMENT_MAP.json',requirements)
f03={k:status for k,status in [('INSTRUMENT_IDENTITY','PARTIAL_CURRENT_ONLY'),('LISTING_STATE','NOT_PROVEN_HISTORICALLY'),('DELISTING_STATE','NOT_PROVEN'),('ELIGIBILITY','NOT_PROVEN'),('DATA_AVAILABILITY','LOCAL_RECEIPT_ONLY'),('PUBLICATION_TIMING','NOT_PROVEN'),('REVISION_CONTROL','OBSERVED_HASH_ONLY')]}
f04={k:status for k,status in [('INSTRUMENT','PARTIAL_CURRENT_ONLY'),('QUANTITY_UNIT','NOT_PROVEN'),('PRICE_UNIT','NOT_PROVEN_FULL_CONTRACT'),('SETTLEMENT','NOT_PROVEN'),('PAYOFF','NOT_PROVEN'),('MULTIPLIER','NOT_PROVEN'),('MARGIN_COLLATERAL','PARTIAL'),('PRICE_TYPE','SUPPORTED_DISTINCTIONS_NO_FILL'),('CLOCK_ADMISSIBILITY','OBSERVED_ONLY_UNRECONCILED')]}
write('DECISIONS.json',{'initiative':'20260911T0233','phase':'3B','F03':{'status':'BLOCKED_CURRENT_EVIDENCE','scope':'Historical cross-sectional universe/ranking; BTC bundle does not establish membership','components':f03,'enabled_subset':None},'F04':{'status':'BLOCKED_CURRENT_EVIDENCE','scope':'BTCUSDT spot/perpetual and BTCUSDT_261225 economic replay','components':f04,'enabled_economic_subset':None,'technical_subset_enabled':['literal metadata reconstruction at recorded collection times','trade/mark/book semantic separation','same-local-clock receipt timeline','dimensional controls on declared units; not actual instrument payoff']},'funding':'FUNDING_REPLAY_NOT_PROVEN','clock_cause':'CAUSE_UNKNOWN','stop_conditions':['B_PRECISE_BLOCKERS','C_NONIDENTIFIABLE_CAPTURED_CLOCK_AND_MISSING_VINTAGE_PROPERTIES','D_BOUNDED_SAVED_SPECIFICATION_SATURATION'],'phase4':{'economic_replay_authorized':False,'scopes_promoted':[]},'scientific_states_unchanged':True,'no_economic_hypothesis_promoted':True})
print('18 precise evidence requirements; both economic gates BLOCKED_CURRENT_EVIDENCE')
