import concurrent.futures
from datetime import datetime, UTC
import hashlib
import importlib.metadata as metadata
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import zipfile
from inventory_migration import ROOTS, TASK, scan

STAGE = TASK/'work/migracao'
ALT = ROOTS['sessoes/20260907-altcoins']/'work/cripto-v1.2'
RUNTIME = Path(sys.base_prefix)
def jwrite(path, obj):
    path.write_text(json.dumps(obj,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
def hashfile(path):
    with Path(path).open('rb') as f:
        return hashlib.file_digest(f,'sha256').hexdigest()
def git(*args):
    return subprocess.check_output(['git','-C',str(ROOTS['projeto']),*args],text=True)
def walked(root):
    for folder, dirs, files in os.walk(root):
        dirs[:] = [d for d in dirs if d not in {'__pycache__','.pytest_cache','.ruff_cache'}]
        for name in files:
            if name.endswith(('.pyc','.pyo')):
                continue
            p = Path(folder)/name
            if p.is_symlink():
                raise ValueError('Unexpected runtime link: '+str(p))
            yield p
def main():
    scan()
    inventory=json.loads((STAGE/'inventory.json').read_text(encoding='utf-8'))
    files=inventory['files']
    config=STAGE/'configuracao'
    config.mkdir(exist_ok=True)
    shutil.copyfile(Path(r'C:\Users\Superleo13\.codex\automations\observar-altcoins-semanalmente\automation.toml'),config/'automation-original.toml')
    shutil.copyfile(Path(r'C:\Users\Superleo13\.codex\attachments\58781ef9-f70f-4a5d-bce2-b326cee9999f\pasted-text.txt'),config/'pedido-original.txt')
    (config/'git-checkouts.txt').write_text(git('worktree','list','--porcelain'),encoding='utf-8')
    (config/'git-status-main.txt').write_text(git('status','--short'),encoding='utf-8')
    environments=[]
    for env in inventory['virtualenvs']:
        root=Path(env)
        packages=[]
        for dist in metadata.distributions(path=[str(root/'Lib/site-packages')]):
            packages.append({'name':dist.metadata['Name'],'version':dist.version})
        environments.append({'source':env,'pyvenv':(root/'pyvenv.cfg').read_text(encoding='utf-8'),'packages':packages,'copied':root == ALT/'.venv'})
    jwrite(config/'ambientes-python.json',environments)
    excluded=[r for r in inventory['omitted'] if r['path'] != str(ALT/'.venv') and r['reason']!='migration staging']
    excluded.append({'path':'**/__pycache__, **/*.pyc, **/*.pyo (runtime)','reason':'generated bytecode; no research records'})
    jwrite(config/'exclusoes.json',excluded)
    for p in walked(ALT/'.venv'):
        files.append({'source':str(p),'archive':'sessoes/20260907-altcoins/work/cripto-v1.2/.venv/'+p.relative_to(ALT/'.venv').as_posix(),'size':p.stat().st_size})
    for p in config.iterdir():
        files.append({'source':str(p),'archive':'configuracao/'+p.name,'size':p.stat().st_size})
    bundle=STAGE/'repositorio-completo.bundle'
    files.append({'source':str(bundle),'archive':'git/repositorio-completo.bundle','size':bundle.stat().st_size})
    records=[]
    def hashed(row):
        p=Path(row['source'])
        before=p.stat()
        digest=hashfile(p)
        after=p.stat()
        if (before.st_mtime_ns,before.st_size)!=(after.st_mtime_ns,after.st_size):
            raise RuntimeError('File changed while reading: '+str(p))
        return {'path':row['archive'],'source':str(p),'size':after.st_size,'mtime_ns':after.st_mtime_ns,'sha256':digest}
    with concurrent.futures.ThreadPoolExecutor(max_workers=8) as pool:
        for i,row in enumerate(pool.map(hashed,files),1):
            records.append(row)
            if i%10000==0:print(f'Hashed {i}/{len(files)}',flush=True)
    unique={r['sha256']:r for r in records}
    print(json.dumps({'files':len(records),'unique':len(unique),'logical_bytes':sum(r['size'] for r in records),'unique_bytes':sum(r['size'] for r in unique.values())}),flush=True)
    with zipfile.ZipFile(STAGE/'dados.zip','w',compression=zipfile.ZIP_DEFLATED,compresslevel=3,allowZip64=True) as z:
        for i,(digest,row) in enumerate(unique.items(),1):
            p=Path(row['source'])
            z.write(p,'objetos/'+digest)
            if i%5000==0:print(f'Packed {i}/{len(unique)} unique files',flush=True)
    # Confirm the bytes in the compressed archive against the independently produced inventory.
    with zipfile.ZipFile(STAGE/'dados.zip') as z:
        for i,digest in enumerate(unique,1):
            with z.open('objetos/'+digest) as f:
                if hashlib.file_digest(f,'sha256').hexdigest()!=digest:
                    raise ValueError('Archive hash mismatch: '+digest)
            if i%5000==0:print(f'Archive checked {i}/{len(unique)}',flush=True)
    changed=[]
    for row in records:
        st=Path(row['source']).stat()
        if (st.st_size,st.st_mtime_ns)!=(row['size'],row['mtime_ns']):
            changed.append(row['source'])
    if changed:raise RuntimeError('Sources changed during snapshot: '+str(changed))
    runtime=[]
    for p in walked(RUNTIME):
        rel=p.relative_to(RUNTIME)
        dest=STAGE/'runtime'/rel
        dest.parent.mkdir(parents=True,exist_ok=True)
        shutil.copyfile(p,dest)
        runtime.append({'path':rel.as_posix(),'sha256':hashfile(dest),'size':dest.stat().st_size})
    manifest={'version':1,'created_utc':datetime.now(UTC).isoformat(),'scope':'crypto project and three identified research workspaces; not a disk image','roots':inventory['roots'],'files':records,'logical_bytes':sum(r['size'] for r in records),'unique_objects':len(unique),'runtime_files':runtime,'runtime_bytes':sum(r['size'] for r in runtime),'runtime_version':sys.version,'git_head':git('rev-parse','HEAD').strip(),'git_remote':'https://github.com/leonardosovienski/cripto-predictor','automation_transferred':False}
    jwrite(STAGE/'MANIFESTO.json',manifest)
    print(json.dumps({'status':'READY_FOR_RESTORE_TEST','files':len(records),'runtime_files':len(runtime),'data_zip_bytes':(STAGE/'dados.zip').stat().st_size,'logical_bytes':manifest['logical_bytes'],'runtime_bytes':manifest['runtime_bytes']},indent=2),flush=True)
if __name__=='__main__':main()
