import logging

ENVELOPE_KEYS: tuple[str, ...]

def emit_event(*args: object, **kwargs: object) -> None: ...
def read_events(path: object) -> list[dict]: ...
def setup_logging(level: str = ..., fmt: str | None = ...) -> None: ...
def get_logger(name: str) -> logging.Logger: ...


